### ISSUE TITLE
τῆν

### ISSUE THREAD

**Issue by zaddok** [Center-for-New-Testament-Restoration/KJTR#2]
I am not sure if the difference in accent compared to others is intentional or accidental here:

τῆν
Matthew 26:7 11
Revelation 19:20 43

Secondly, I am not sure if τἣν in Col 1:4 is a typo, or deliberate.  Im not sure if I should report it as a possible typo, or if it was intentional.

τὴν ἀγάπην τἣν εἰς πάντας

**Comment by greekcntr** [comment]
Should be fixed in next update.
