### ISSUE TITLE
ἐιμι in Revelation 1:11

### ISSUE THREAD

**Issue by scripturial** [Center-for-New-Testament-Restoration/KJTR#4]
I think the breathing may be incorrect on ἐιμι in Revelation 1:11. 

(Im not sure if the goals for the texts are generally to be modern, or if sometimes the accents may look odd because they are following a specific manuscript. Is it a general rule that all of the CNTR texts are aiming for modern pronunciation?)

**Comment by greekcntr** [comment]
You are correct. That was a typo brought over from Stephanus 1550. It should be corrected with my the next upload.
