### ISSUE TITLE
Possible fixes needed for αὐτόν

### ISSUE THREAD

**Issue by scripturial** [Center-for-New-Testament-Restoration/KJTR#7]
Parsing(PERSONAL_PRONOUN | MASCULINE | ACCUSATIVE | SINGULAR)
"αυτόν"
"Hebrews 2:7 16"

Parsing(PERSONAL_PRONOUN | MASCULINE | ACCUSATIVE | SINGULAR)
"αὐτον"
"Revelation 13:10 15"

Parsing(PERSONAL_PRONOUN | MASCULINE | ACCUSATIVE | SINGULAR)
"ἀυτόν"
"Hebrews 12:3 9"

Parsing(PERSONAL_PRONOUN | MASCULINE | NOMINATIVE | SINGULAR)
"αὑτός"
"Matthew 6:4 18",  "1 Corinthians 7:13 8"

**Comment by greekcntr** [comment]
These should all be fixed in the next update.
